// automatically generated by the FlatBuffers compiler, do not modify

package CoffeeTime.InputEvents;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Mouse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Mouse getRootAsMouse(ByteBuffer _bb) { return getRootAsMouse(_bb, new Mouse()); }
  public static Mouse getRootAsMouse(ByteBuffer _bb, Mouse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Mouse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String type() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String button() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer buttonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer buttonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public CoffeeTime.InputEvents.Position position() { return position(new CoffeeTime.InputEvents.Position()); }
  public CoffeeTime.InputEvents.Position position(CoffeeTime.InputEvents.Position obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMouse(FlatBufferBuilder builder,
      int typeOffset,
      int buttonOffset,
      int positionOffset) {
    builder.startTable(3);
    Mouse.addPosition(builder, positionOffset);
    Mouse.addButton(builder, buttonOffset);
    Mouse.addType(builder, typeOffset);
    return Mouse.endMouse(builder);
  }

  public static void startMouse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(0, typeOffset, 0); }
  public static void addButton(FlatBufferBuilder builder, int buttonOffset) { builder.addOffset(1, buttonOffset, 0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addOffset(2, positionOffset, 0); }
  public static int endMouse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Mouse get(int j) { return get(new Mouse(), j); }
    public Mouse get(Mouse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

