// automatically generated by the FlatBuffers compiler, do not modify

package CoffeeTime.Output.Frame;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Frame extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Frame getRootAsFrame(ByteBuffer _bb) { return getRootAsFrame(_bb, new Frame()); }
  public static Frame getRootAsFrame(ByteBuffer _bb, Frame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Frame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CoffeeTime.Output.Frame.Sound sounds(int j) { return sounds(new CoffeeTime.Output.Frame.Sound(), j); }
  public CoffeeTime.Output.Frame.Sound sounds(CoffeeTime.Output.Frame.Sound obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int soundsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public CoffeeTime.Output.Frame.Sound.Vector soundsVector() { return soundsVector(new CoffeeTime.Output.Frame.Sound.Vector()); }
  public CoffeeTime.Output.Frame.Sound.Vector soundsVector(CoffeeTime.Output.Frame.Sound.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public CoffeeTime.Output.Frame.Sprite sprites(int j) { return sprites(new CoffeeTime.Output.Frame.Sprite(), j); }
  public CoffeeTime.Output.Frame.Sprite sprites(CoffeeTime.Output.Frame.Sprite obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int spritesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public CoffeeTime.Output.Frame.Sprite.Vector spritesVector() { return spritesVector(new CoffeeTime.Output.Frame.Sprite.Vector()); }
  public CoffeeTime.Output.Frame.Sprite.Vector spritesVector(CoffeeTime.Output.Frame.Sprite.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFrame(FlatBufferBuilder builder,
      int soundsOffset,
      int spritesOffset) {
    builder.startTable(2);
    Frame.addSprites(builder, spritesOffset);
    Frame.addSounds(builder, soundsOffset);
    return Frame.endFrame(builder);
  }

  public static void startFrame(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addSounds(FlatBufferBuilder builder, int soundsOffset) { builder.addOffset(0, soundsOffset, 0); }
  public static int createSoundsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSoundsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSprites(FlatBufferBuilder builder, int spritesOffset) { builder.addOffset(1, spritesOffset, 0); }
  public static int createSpritesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSpritesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFrame(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Frame get(int j) { return get(new Frame(), j); }
    public Frame get(Frame obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

