// automatically generated by the FlatBuffers compiler, do not modify

package CoffeeTime.Output.Frame;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Size extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Size getRootAsSize(ByteBuffer _bb) { return getRootAsSize(_bb, new Size()); }
  public static Size getRootAsSize(ByteBuffer _bb, Size obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Size __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double height() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double width() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createSize(FlatBufferBuilder builder,
      double height,
      double width) {
    builder.startTable(2);
    Size.addWidth(builder, width);
    Size.addHeight(builder, height);
    return Size.endSize(builder);
  }

  public static void startSize(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addHeight(FlatBufferBuilder builder, double height) { builder.addDouble(0, height, 0.0); }
  public static void addWidth(FlatBufferBuilder builder, double width) { builder.addDouble(1, width, 0.0); }
  public static int endSize(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Size get(int j) { return get(new Size(), j); }
    public Size get(Size obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

